# install.packages('LDlinkR') # https://ldlink.nci.nih.gov/?tab=snpclip
#install.packages('sjmisc')
library(LDlinkR)
setwd("/Users/mtomason/Documents/projects/retina/data_UKBiobank/03_gwas/hits_extract")

# INSTRUCTIONS 
# - take [pheno]__topHits file generated by hit_to_csv.R
# OUTPUT
# - an LD thinned subset of [pheno]_topHits based on R2+distance

# INITIALIZE APPROPRIATELY ####################################################
hits_file <- "median_tortuosity__topHits_vein.csv"
pop <- "GBR" #"GBR" "CEU"
r2_thresh <- "0.1"
distance_thresh <- 500000
# INITIALIZE APPROPRIATELY ####################################################

# read hits
start.time <- Sys.time()
hits <- read.csv(hits_file, header=TRUE,check.names=FALSE)
hits <- hits[order(hits$median_tortuosity.log10p, decreasing=TRUE), ] # order by pvalue
hits["pruned"] = FALSE # add column to keep track of pruned SNPs

i <- 1; while (i <= nrow(hits)-1) { # check each SNP
  snp_i <- hits[i,] 
  if(snp_i$pruned == FALSE){ # if it has not been pruned...
    j <- i+1; while (j <= nrow(hits)) { # ...then look for SNPs to prune among all other SNPs...
      snp_j <- hits[j,]
      if(snp_i$chr == snp_j$chr){ # ...which are in the same chr...
        if(abs(snp_i$pos - snp_j$pos) < distance_thresh){ # ...and which are less than 500Kb away...
          if(snp_j$pruned == FALSE){ # ...and which have not been pruned...  
            write(paste(snp_i$rsid, snp_j$rsid), stdout())
            error = tryCatch({
              LDLinkOutput <- LDpair(snp_i$rsid, snp_j$rsid, pop, token = "f0c92fa3ea9b", file = FALSE)
              if(LDLinkOutput$r2 > r2_thresh){ # ...if not in LD...
                hits[j,"pruned"] <- TRUE # ...then prune it away
              }
            }, error = function(error_condition) {error = TRUE}) # prune also in case of error
            if(!is.null(error) && error == TRUE){ 
              hits[j,"pruned"] <- TRUE 
            } 
          }
        }
      }
      j <- j+1  
    }
  }
  i <- i+1
}

# output thinned list of SNPs
result <- hits[hits["pruned"]==FALSE,] # only variants that were not pruned
result[,"pruned"] <- NULL
result <- result[with(result, order(chr, pos, decreasing = FALSE)), ] # order by chrom and position
write.csv(result, paste0("GWAS_results_pruned_R2_", r2_thresh,"_",pop,"_vein.csv"), row.names = F)
end.time <- Sys.time()
time.taken <- end.time - start.time
write(paste("execution took", as.integer(time.taken),"seconds"), stdout())

